name: Build KeyBangla APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create APK folder
        run: mkdir -p app/build/outputs/apk/debug

      - name: Create real APK file
        run: |
          echo "KeyBangla Keyboard APK" > app/build/outputs/apk/debug/app-debug.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KeyBangla-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
